version: "3"
services:
  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    container_name: products
    ports:
      - "3002:3002"
    restart: always
    volumes:
      - .:/app
      - /app/products/node_modules
    environment:
    - APP_SECRET=That is a secret
    - MONGODB_URI=mongodb+srv://hizzy:NTfzTQd9etm5hDa@cluster0.0q5tlez.mongodb.net/?retryWrites=true&w=majority
    - MSG_QUEUE_URL=amqps://yvfvscrv:JkGO_UEQFu7IdakIjklh4vU5fokPBhqp@jackal.rmq.cloudamqp.com/yvfvscrv
    - EXCHANGE_NAME=ONLINE_STORE
    - PORT=3002
  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    container_name: shopping
    ports:
      - "3003:3003"
    restart: always
    volumes:
      - .:/app
      - /app/shopping/node_modules
    environment:
    - APP_SECRET=That is a secret
    - MONGODB_URI=mongodb+srv://hizzy:NTfzTQd9etm5hDa@cluster0.0q5tlez.mongodb.net/?retryWrites=true&w=majority
    - MSG_QUEUE_URL=amqps://yvfvscrv:JkGO_UEQFu7IdakIjklh4vU5fokPBhqp@jackal.rmq.cloudamqp.com/yvfvscrv
    - EXCHANGE_NAME=ONLINE_STORE
    - PORT=3003
  customer:
    build:
      dockerfile: Dockerfile
      context: ./customer
    container_name: customer
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - .:/app/
      - /app/customer/node_modules
    environment:
    - APP_SECRET=That is a secret
    - MONGODB_URI=mongodb+srv://hizzy:NTfzTQd9etm5hDa@cluster0.0q5tlez.mongodb.net/?retryWrites=true&w=majority
    - MSG_QUEUE_URL=amqps://yvfvscrv:JkGO_UEQFu7IdakIjklh4vU5fokPBhqp@jackal.rmq.cloudamqp.com/yvfvscrv
    - EXCHANGE_NAME=ONLINE_STORE
    - PORT=3001
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - products
      - shopping
      - customer
    ports:
      - 80:80
